### ISSUE TITLE
Dead code in paper_classifier_predictor.py

### ISSUE THREAD

**Issue by ducalpha** [allenai/allennlp-as-a-library-example#17]
https://github.com/allenai/allennlp-as-a-library-example/blob/583f2fd51f9025341c4647c7070196f117c6ede4/my_library/predictors/paper_classifier_predictor.py#L21

The changes to 0.6.1 removes the usages of `all_labels` but its initialization is still here. It made me very confusing when I tried to understand "how the predictor found all the labels?" and it turned out this is dead code.

**Comment by matt-gardner** [comment]
Thanks!
